# OpenDKIM configuration
Syslog                  yes
SyslogSuccess           yes
LogWhy                  yes
Canonicalization        relaxed/simple
ExternalIgnoreList      refile:/etc/opendkim/hosts
InternalHosts           refile:/etc/opendkim/hosts
KeyFile                 /etc/opendkim/keys/default.private
KeyTable                refile:/etc/opendkim/key.table
SigningTable            refile:/etc/opendkim/signing.table
Socket                  inet:8891 @localhost
Domain                  *
Mode                    sv
SubDomains              yes
AutoRestart             yes
AutoRestartRate         10/1M
Background              yes
DNSTimeout              5
SignatureAlgorithm      rsa-sha256
OversignHeaders         From
